<img width="800px" src="../fidle/img/00-Fidle-header-01.svg"></img>

# <!-- TITLE --> [SCRATCH1] - Scratchbook
<!-- DESC --> A scratchbook for small examples
<!-- AUTHOR : Jean-Luc Parouty (CNRS/SIMaP) -->

## Objectives :
 - Take a quick look at thousands of little things

## Inside this scratchbook :

[1 - LSTM Keras layer](#1---LSTM-Keras-layer)


# One init to rule them all

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator

import numpy as np
import math, random

## 1 - LSTM Keras layer

In [17]:
inputs  = tf.random.normal([32, 20, 8])

lstm    = tf.keras.layers.LSTM(16)
output  = lstm(inputs)

print('Inputs shape is : ', inputs.shape)
print('Output shape is : ', output.shape)

Inputs shape is :  (32, 20, 8)
Output shape is :  (32, 16)


In [29]:
lstm = tf.keras.layers.LSTM(20, return_sequences=True, return_state=True)

output, memory_state, carry_state = lstm(inputs)

print('Output shape : ', output.shape)
print('Memory state : ', memory_state.shape)
print('Carry  state : ', carry_state.shape)


Output shape :  (32, 20, 20)
Memory state :  (32, 20)
Carry  state :  (32, 20)


In [30]:
# --- See the last vector of the output
output[-1,-1]

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([-0.0174353 , -0.05081974, -0.04655018, -0.32286584,  0.04371583,
        0.00813733,  0.19542098,  0.00932144,  0.05667783,  0.40550408,
       -0.05310456,  0.05051089,  0.16859534, -0.15717325, -0.06320478,
        0.08673657,  0.14486386, -0.00984205, -0.01904174,  0.18143968],
      dtype=float32)>

In [33]:
# ---- Memory state is the last output
memory_state[-1]

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([-0.0174353 , -0.05081974, -0.04655018, -0.32286584,  0.04371583,
        0.00813733,  0.19542098,  0.00932144,  0.05667783,  0.40550408,
       -0.05310456,  0.05051089,  0.16859534, -0.15717325, -0.06320478,
        0.08673657,  0.14486386, -0.00984205, -0.01904174,  0.18143968],
      dtype=float32)>

In [32]:
carry_state[-1]

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([-0.03481168, -0.11190109, -0.07686044, -0.74444455,  0.09519605,
        0.01375953,  0.4971139 ,  0.02084009,  0.0941705 ,  0.6564664 ,
       -0.07501178,  0.11393531,  0.5034484 , -0.46511504, -0.20532629,
        0.12056433,  0.42408258, -0.01648504, -0.03014653,  0.44732788],
      dtype=float32)>